// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Emplois.API.Data;

#nullable disable

namespace ModernRecrut.Emplois.API.Migrations
{
    [DbContext(typeof(ModernRecrutEmploisContext))]
    [Migration("20230512215625_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("ModernRecrut.Emplois.API.Models.OffreEmploi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAffichage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDeFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poste")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OffreEmploi");
                });
#pragma warning restore 612, 618
        }
    }
}
