// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Postulations.API.Data;

#nullable disable

namespace ModernRecrut.Postulations.API.Migrations
{
    [DbContext(typeof(ModernRecrutPostulationsContext))]
    [Migration("20230618164920_MigrationInitiale")]
    partial class MigrationInitiale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");
#pragma warning restore 612, 618
        }
    }
}
